# Generated by Django 5.2.4 on 2025-07-09 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for display', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=200)),
                ('author', models.CharField(help_text='Author name(s)', max_length=200)),
                ('description', models.TextField(help_text='Book description/summary')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=8)),
                ('pages', models.PositiveIntegerField(help_text='Number of pages')),
                ('publication_date', models.DateField(help_text='When the book was published')),
                ('in_stock', models.BooleanField(default=True, help_text='Is this book currently available?')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Number of copies in stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Book category (Fiction, Science, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='products.category')),
                ('tags', models.ManyToManyField(blank=True, help_text="Tags like 'bestseller', 'new-release', etc.", related_name='books', to='products.tag')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
